# Generated by Django 4.1 on 2023-05-08 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cloudflare', '0008_cloudflaremodel_account_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareWebsites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cloudflare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cloudflare.cloudflaremodel')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
