FROM python:3.9-buster
ENV PYTHONUNBUFFERED=1

RUN mkdir /code
WORKDIR /code

COPY requirements requirements/
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /code/
COPY ./entrypoint.sh /
ENTRYPOINT ["sh", "entrypoint.sh"]

# note: if you don't want to run collectstatic on every deploy you can remove this line.
RUN python manage.py collectstatic --noinput --settings=Home.settings_do
