default_context:
  _pegasus_version: '2022.6'
  author_name: Mohamed
  ci: github_actions
  css_framework: bootstrap
  css_theme: bootstrap-material
  database: postgres
  deploy_platform: digital_ocean_app_platform
  description: Let's get your pages crawled and indexed.
  domain_name: localhost:8000
  email: isse.mohamed@gmail.com
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: htmx
  project_name: Indexer App
  project_slug: Home
  stripe_payment_mode: checkout
  subscription_billing_model: per_unit
  use_api_keys: y
  use_docker: y
  use_impersonation: n
  use_sentry: n
  use_subscriptions: y
  use_teams: y
  use_wagtail: y
