# Generated by Django 3.2.13 on 2023-04-27 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileFriendlyPages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('request_screenshot', models.FileField(blank=True, null=True, upload_to='media/mobile_friendly/')),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('seconds', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('results', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField()),
                ('rank_group', models.IntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('date_tracking', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mobile_friendly_pages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MobileFriendWeb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('website', models.URLField(help_text='Your Website')),
                ('pages', models.TextField(blank=True, help_text='List of pages you want to mobile friendly create. 1 Url Per Line', null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('times_checked', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mobile_friendly_web',
                'managed': False,
            },
        ),
    ]
