
databases:
- engine: PG
  name: Home-db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
- cluster_name: Home-redis
  engine: REDIS
  name: Home-redis
  production: true
  version: "6"
name: Home
region: nyc
services:
- dockerfile_path: Dockerfile.web
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${Home-db.DATABASE_URL}
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: Home.settings_do
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: 'gudcGvYXQNTANGpsuaoJReduAZseOgcoDECOcrqO'
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${Home-redis.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: user/Home
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: Home-web
  routes:
  - path: /
  run_command: gunicorn --bind 0.0.0.0:8080 --workers 1 --threads 8 --timeout 0 --worker-tmp-dir /dev/shm Home.wsgi:application
workers:
- dockerfile_path: Dockerfile.web
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${Home-db.DATABASE_URL}
  - key: DJANGO_SETTINGS_MODULE
    scope: RUN_AND_BUILD_TIME
    value: Home.settings_do
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    value: 'gudcGvYXQNTANGpsuaoJReduAZseOgcoDECOcrqO'
  - key: REDIS_URL
    scope: RUN_TIME
    value: ${Home-redis.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: user/Home
  instance_count: 1
  instance_size_slug: basic-xs
  name: Home-celery
  run_command: celery -A Home worker -l INFO --pool=gevent
