# Generated by Django 3.2.13 on 2022-08-31 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('key', models.CharField(blank=True, max_length=60, null=True)),
                ('nameServers', models.TextField(blank=True, null=True)),
                ('resP', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CloudflareModelUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloudflare',
                'verbose_name_plural': 'Cloudflare',
            },
        ),
    ]
