# Generated by Django 3.2.13 on 2022-08-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloudflare', '0002_cloudflaredns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudflaredns',
            options={'verbose_name': 'Cloudflare Site DNS', 'verbose_name_plural': 'CloudflareDNS'},
        ),
        migrations.AlterField(
            model_name='cloudflaredns',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
