# Generated by Django 3.2.13 on 2022-09-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloudflare', '0003_auto_20220831_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudflaredns',
            name='deleteDNS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
