# Generated by Django 3.2.13 on 2022-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloudflare', '0004_cloudflaredns_deletedns'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudflaredns',
            name='cloudid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cloudflaredns',
            name='cloudname',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
