# Generated by Django 3.2.13 on 2023-04-27 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cloudflare', '0006_cloudflaredns_pagerule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareDNSInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_id', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cloudflare_dns_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CloudflareModelUrl',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone_id', models.CharField(blank=True, max_length=500, null=True)),
                ('zone_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Cloudflare_resp_url',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CloudflarePageRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zone_id', models.CharField(blank=True, max_length=500, null=True)),
                ('rule_id', models.CharField(blank=True, max_length=500, null=True)),
                ('targets', models.CharField(blank=True, max_length=500, null=True)),
                ('actions', models.CharField(blank=True, max_length=500, null=True)),
                ('priority', models.TextField(blank=True, null=True)),
                ('resp', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cloudflare_page_rule',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='cloudflaremodel',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloudflaremodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='cloudflaremodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
