# Generated by Django 4.1 on 2023-05-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloudflare', '0007_auto_20230427_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudflaremodel',
            name='account_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cloudflaremodel',
            name='account_token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cloudflaremodel',
            name='key',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
