# Generated by Django 3.2.13 on 2022-09-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_yacss_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spintax7',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
