# Generated by Django 3.2.13 on 2022-09-21 23:40

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Content', '0004_alter_spintax7_content2'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordIdeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', models.CharField(blank=True, max_length=300, null=True)),
                ('pageUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('result', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KeywordIdeas_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Keyword Idea',
                'verbose_name_plural': 'Keyword Ideas',
            },
        ),
    ]
