# Generated by Django 3.2.13 on 2022-06-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0004_remove_website_indexapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='pages',
            field=models.TextField(help_text='List of pages you want to index. 1 Url Per Line'),
        ),
    ]
