# Generated by Django 3.2.13 on 2022-06-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0006_auto_20220630_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='jsonFile',
            field=models.TextField(blank=True, help_text='Response From API', max_length=500, null=True),
        ),
    ]
