# Generated by Django 3.2.13 on 2022-07-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0007_alter_website_jsonfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='pages',
            field=models.TextField(blank=True, help_text='List of pages you want to index. 1 Url Per Line', null=True),
        ),
    ]
