# Generated by Django 3.2.13 on 2022-07-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0008_alter_website_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='JsonResponse',
            field=models.JSONField(blank=True, help_text='Paste Json Key from Index Api Above', null=True, verbose_name='Json Key'),
        ),
    ]
