# Generated by Django 3.2.13 on 2022-07-02 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indexer', '0010_alter_website_jsonfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.URLField(help_text='Your Website')),
                ('results', models.TextField(help_text='Paste Json Key from Index Api Above', verbose_name='Json Key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SitemapUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
