# Generated by Django 3.2.13 on 2022-07-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0011_sitemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemap',
            name='results',
            field=models.TextField(blank=True, help_text='Sitemap Results', null=True, verbose_name='Sitemap Results'),
        ),
        migrations.AlterField(
            model_name='sitemap',
            name='website',
            field=models.URLField(help_text='Website to Crawl Sitemap'),
        ),
    ]
