# Generated by Django 3.2.13 on 2022-07-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0013_alter_sitemap_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='JsonResponse',
            field=models.TextField(blank=True, help_text='Paste Json Key from Index Api Above', null=True, verbose_name='Json Key'),
        ),
    ]
