# Generated by Django 3.2.13 on 2022-07-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0015_auto_20220714_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='times_indexed',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
