# Generated by Django 3.2.13 on 2022-07-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0016_auto_20220720_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='check_index',
            field=models.BooleanField(default=False),
        ),
    ]
