# Generated by Django 3.2.13 on 2022-07-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0017_website_check_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='JsonResponse',
            field=models.TextField(blank=True, help_text='Check Index Box Below to run indexed checker', null=True, verbose_name='Check Indexed Status'),
        ),
    ]
