# Generated by Django 3.2.13 on 2022-08-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0019_auto_20220804_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='times_indexedRate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
