# Generated by Django 3.2.13 on 2022-08-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0020_website_times_indexedrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='NonindexedPages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='RunIndexer5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='disableIndexing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='indexedPages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
