# Generated by Django 3.2.13 on 2022-10-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0021_auto_20220805_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexerPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, max_length=255, null=True)),
                ('index_status', models.IntegerField()),
                ('indexed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indexer_pages',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='indexapi',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
