# Generated by Django 3.2.13 on 2022-10-29 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0022_auto_20221026_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loghistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'tbl_loghistory',
                'managed': False,
            },
        ),
    ]
