# Generated by Django 3.2.13 on 2022-11-01 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0023_loghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexWebTracking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_right', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'index_website_dt_tracking',
                'managed': False,
            },
        ),
    ]
