# Generated by Django 3.2.13 on 2022-11-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0024_indexwebtracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexapi',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
