# Generated by Django 3.2.13 on 2022-08-31 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.URLField()),
                ('status', models.CharField(max_length=60)),
                ('niche', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SiteNetworkUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Backlinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backlink', models.URLField()),
                ('anchor', models.CharField(max_length=60)),
                ('rebuildPage', models.CharField(max_length=60)),
                ('numberOfLinks', models.IntegerField(default=1)),
                ('DR', models.IntegerField(default=0)),
                ('traffic', models.IntegerField(default=0)),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SiteNetwork.sites')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
