# Generated by Django 3.2.13 on 2022-08-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backlinks',
            options={'verbose_name': 'Backlink', 'verbose_name_plural': 'Backlinks'},
        ),
        migrations.AlterModelOptions(
            name='sites',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterField(
            model_name='backlinks',
            name='DR',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='backlinks',
            name='anchor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='backlinks',
            name='backlink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backlinks',
            name='numberOfLinks',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='backlinks',
            name='rebuildPage',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='backlinks',
            name='traffic',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='niche',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
