# Generated by Django 3.2.13 on 2022-09-03 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SiteNetwork', '0002_auto_20220831_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sites',
            options={'verbose_name': 'Potential Site', 'verbose_name_plural': 'Potential Sites'},
        ),
        migrations.CreateModel(
            name='DigitalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.URLField(blank=True, null=True)),
                ('nameserver', models.CharField(blank=True, max_length=60, null=True)),
                ('registrar', models.CharField(blank=True, max_length=60, null=True)),
                ('expireDate', models.DateField(blank=True, null=True)),
                ('traffic', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('niche', models.CharField(blank=True, max_length=60, null=True)),
                ('importance', models.CharField(blank=True, max_length=60, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DigitalPropertyUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Digital Property',
                'verbose_name_plural': 'Digital Properties',
            },
        ),
    ]
