# Generated by Django 3.2.13 on 2022-09-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteNetwork', '0003_auto_20220903_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalproperty',
            name='importance',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='digitalproperty',
            name='nameserver',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitalproperty',
            name='niche',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='digitalproperty',
            name='registrar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='digitalproperty',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
