# Generated by Django 3.2.13 on 2022-09-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteNetwork', '0004_auto_20220903_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproperty',
            name='Whois',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='digitalproperty',
            name='domain',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
