# Generated by Django 3.2.13 on 2022-09-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteNetwork', '0006_auto_20220903_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalPropertyClient',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('SiteNetwork.digitalproperty',),
        ),
    ]
